### ISSUE TITLE
Segmentation fault in parhip

### ISSUE THREAD

**Issue by christopherosthues** [schulzchristian/KaHIP#34]
I'm getting segmentation faults using parhip for undirected graphs with large edge weights.
I have also graphs with nodes that have no edges. For those graphs I'm getting  an std::length_error. See the attached files for graph examples.

[graph1.txt](https://github.com/schulzchristian/KaHIP/files/3186922/graph1.txt)
[graph2.txt](https://github.com/schulzchristian/KaHIP/files/3186923/graph2.txt)

**Comment by schulzchristian** [comment]
Hey Christopher, 

the public version of ParHIP cannot read edge weights atm since I forgot to integrate it. If you need a version that can send me an email and I will send it to you. Integration may take a little bit of time. 
I am looking into the issue with the second graph now.


Best
Christian

**Comment by schulzchristian** [comment]
btw in the second case, the graph is most likely ``too small''.

**Comment by schulzchristian** [comment]
This is fixed now. The problem really was that the graph is ``too small''. The coarsest level is done with an evolutionary algorithm that also partitions the graph into blocks larger than the specified number of blocks. It turned out that the evolutionary algorithm tried to obtain a partition of a graph with 5 vertices into k > 5 blocks.

**Comment by christopherosthues** [comment]
Great. Thank you.

**Comment by christopherosthues** [comment]
I'm still getting the std::length_error for the unweighted graphs caused by a std::vector in the parallel_graph_io::readGraphWeightedFlexible function.

**Comment by schulzchristian** [comment]
How many processes are you using? The graph is probably again too small to be partitioned by many cores.

**Comment by christopherosthues** [comment]
In this case I'm using 4 processes for a graph with 5 nodes.

**Comment by schulzchristian** [comment]
ah ok. Please just use reasonable sized inputs for the parallel code. If you want to partition small graphs, just use the sequential version. I am sure I could implement error handling for this, but I really would prefer doing actual research. I have now put this onto my todo list for the next release.

**Comment by christopherosthues** [comment]
ok. Thanks.
